package com.docomostar.ui.ogl;

public interface GraphicsOGL {
    void glActiveTexture(int a0);
    void glAlphaFunc(int a0, float a1);
    void glBindBuffer(int a0, int a1);
    void glBindTexture(int a0, int a1);
    void glBlendFunc(int a0, int a1);
    void glBufferData(int a0, com.docomostar.ui.ogl.DirectBuffer a1, int a2);
    void glBufferSubData(int a0, int a1, com.docomostar.ui.ogl.DirectBuffer a2);
    void glClear(int a0);
    void glClearColor(float a0, float a1, float a2, float a3);
    void glClientActiveTexture(int a0);
    void glColor4f(float a0, float a1, float a2, float a3);
    void glColorMask(boolean a0, boolean a1, boolean a2, boolean a3);
    void glColorPointer(int a0, int a1, int a2, int a3);
    void glColorPointer(int a0, int a1, int a2, com.docomostar.ui.ogl.DirectBuffer a3);
    void glCompressedTexImage2D(int a0, int a1, int a2, int a3, int a4, int a5, com.docomostar.ui.ogl.ByteBuffer a6);
    void glCopyTexImage2D(int a0, int a1, int a2, int a3, int a4, int a5, int a6, int a7);
    void glCullFace(int a0);
    void glCurrentPaletteMatrixOES(int a0);
    void glDeleteBuffers(int[] a0);
    void glDeleteTextures(int[] a0);
    void glDepthFunc(int a0);
    void glDepthMask(boolean a0);
    void glDisable(int a0);
    void glDisableClientState(int a0);
    void glDrawArrays(int a0, int a1, int a2);
    void glDrawElements(int a0, int a1, int a2, int a3);
    void glDrawElements(int a0, int a1, com.docomostar.ui.ogl.DirectBuffer a2);
    void glEnable(int a0);
    void glEnableClientState(int a0);
    void glFlush();
    void glFogf(int a0, float a1);
    void glFogfv(int a0, float[] a1);
    void glFrontFace(int a0);
    void glGenBuffers(int[] a0);
    void glGenTextures(int[] a0);
    int glGetError();
    void glGetIntegerv(int a0, int[] a1);
    void glHint(int a0, int a1);
    void glLightModelf(int a0, float a1);
    void glLightModelfv(int a0, float[] a1);
    void glLightf(int a0, int a1, float a2);
    void glLightfv(int a0, int a1, float[] a2);
    void glLoadMatrixf(float[] a0);
    void glMaterialf(int a0, int a1, float a2);
    void glMaterialfv(int a0, int a1, float[] a2);
    void glMatrixIndexPointerOES(int a0, int a1, int a2, int a3);
    void glMatrixMode(int a0);
    void glMultMatrixf(float[] a0);
    void glNormalPointer(int a0, int a1, int a2);
    void glNormalPointer(int a0, int a1, com.docomostar.ui.ogl.DirectBuffer a2);
    void glPixelStorei(int a0, int a1);
    void glPolygonOffset(float a0, float a1);
    void glPopMatrix();
    void glPushMatrix();
    void glScissor(int a0, int a1, int a2, int a3);
    void glShadeModel(int a0);
    void glTexCoordPointer(int a0, int a1, int a2, int a3);
    void glTexCoordPointer(int a0, int a1, int a2, com.docomostar.ui.ogl.DirectBuffer a3);
    void glTexEnvf(int a0, int a1, float a2);
    void glTexEnvfv(int a0, int a1, float[] a2);
    void glTexImage2D(int a0, int a1, int a2, int a3, int a4, int a5, int a6, int a7, com.docomostar.ui.ogl.DirectBuffer a8);
    void glTexParameterf(int a0, int a1, float a2);
    void glTexSubImage2D(int a0, int a1, int a2, int a3, int a4, int a5, int a6, int a7, com.docomostar.ui.ogl.DirectBuffer a8);
    void glVertexPointer(int a0, int a1, int a2, int a3);
    void glVertexPointer(int a0, int a1, int a2, com.docomostar.ui.ogl.DirectBuffer a3);
    void glViewport(int a0, int a1, int a2, int a3);
    void glWeightPointerOES(int a0, int a1, int a2, int a3);
}
